### PR TITLE
Update adafruit-stepper-motor-hat.toml

### PR DESCRIPTION
**Pull request by ddkohler**
* allow for no microsteps (tested and working on hardware)
* docstring clarifies allowed values of microsteps

please wait for testing before merging.

### CODE REVIEW

**Comment by ksunden** [comment]
I don't fully see why null needs to be the non microstepping... why not just `1`, it is equivalent conceptually? (even if the code needs to be adjusted potentially.

It really is just "usteps/full step"

**Comment by ddkohler** [comment]
@ksunden that is fair--microstepping=1 is intuitive for "no microstepping".  I was just trying to follow conventions of our [dependency](https://docs.circuitpython.org/projects/motor/en/latest/api.html#adafruit_motor.stepper.StepperMotor) for an easy fix.  But again, it's not clear to me yet that `adafruit-circuitpython-motorkit` supports microstepping off.

microstepping=1 currently does not work (though our OPA4 daemons had microstepping=1 in config...did support for this recently break?)

**Comment by ksunden** [comment]
So, the direct dependecy [MotorKit](https://github.com/adafruit/Adafruit_CircuitPython_MotorKit/blob/main/adafruit_motorkit.py#L63) doesn't actually specify the behavior of None (though I agree that if it were passed it would work as you expect... except that our code would certainly need to be updated. specificially where we say that the step style is `MICROSTEP` in our code.

That said, I don't think there is any difference in actual behavior of the motors when you do microstepping = 1 compared to doing full stepping (it's not _super_ trivial, but I think it works out to doing the same thing) That's why I didn't bother implementing checks for full stepping previously.

**Comment by ddkohler** [comment]
Sounds good to me. I will update this PR so that microstepping allows positive integers, with 1 working as no microstepping.

**Comment by ddkohler** [comment]
After testing and inspection, I have found that Motorkit does not support microsteps of "1".  Implementing step size now as a stepping "style", which is in line with the Adafruit class implementation.

**Pull request merged**
